create table if not exists categorias (
    id bigint generated by default as identity primary key,
    nome text not null unique
);

create table if not exists postagens (
    id bigint generated by default as identity primary key,
    titulo text not null,
    conteudo text not null,
    categoria text not null,
    criado_em timestamp with time zone default now()
);

insert into categorias (nome)
values ('games')
on conflict (nome) do nothing;